name: Debricked scan

on: [push]

jobs:
  vulnerabilities-scan:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: debricked/actions/cache@v3
      - uses: debricked/actions/scan-non-docker@v3
        env:
          DEBRICKED_TOKEN: ${{ secrets.DEBRICKED_TOKEN }}
